Traceback (most recent call last):
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#@title Application
#@markdown Suppose there exists a telescope installation on a remote island tasked solely with the purpose of capturing images of Saturn. One evening, a particularly stunning image is captured and the scientists on the island wish to send it to their colleagues.
#@markdown
#@markdown ---
#@markdown *Execute this cell to retrieve image.*
import numpy as np
import plotly.express as px
import imageio as iio
import xarray as xr

# Despite the description above, this image was captured by NASA from a telescope in space.
img = iio.imread('https://images-assets.nasa.gov/image/PIA05982/PIA05982~medium.jpg')

fig = px.imshow(img)
fig.update_layout(showlegend=False)
fig.update_xaxes(visible=False)
fig.update_yaxes(visible=False)
fig.update_layout(autosize = False, width = 1280, height = 663)
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [2], line 7[0m
[1;32m      1[0m [38;5;66;03m#@title Application[39;00m
[1;32m      2[0m [38;5;66;03m#@markdown Suppose there exists a telescope installation on a remote island tasked solely with the purpose of capturing images of Saturn. One evening, a particularly stunning image is captured and the scientists on the island wish to send it to their colleagues.[39;00m
[1;32m      3[0m [38;5;66;03m#@markdown[39;00m
[1;32m      4[0m [38;5;66;03m#@markdown ---[39;00m
[1;32m      5[0m [38;5;66;03m#@markdown *Execute this cell to retrieve image.*[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m----> 7[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexpress[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpx[39;00m
[1;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mimageio[39;00m [38;5;28;01mas[39;00m [38;5;21;01miio[39;00m
[1;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mxarray[39;00m [38;5;28;01mas[39;00m [38;5;21;01mxr[39;00m

[0;31mModuleNotFoundError[0m: No module named 'plotly'
ModuleNotFoundError: No module named 'plotly'

